name: robots-txt
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py313ha0c97b7_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - brotlicffi=1.0.9.2=py313h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.9.9=hca03da5_0
  - cachetools=5.5.2=pyhd8ed1ab_0
  - certifi=2025.8.3=py313hca03da5_0
  - cffi=1.17.1=py313h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cryptography=46.0.1=py313h4d9e278_3
  - expat=2.7.1=h313beb8_0
  - frozenlist=1.7.0=py313hf28abc0_0
  - google-ai-generativelanguage=0.6.15=pyhd8ed1ab_0
  - google-api-core=2.25.1=pyhd8ed1ab_0
  - google-api-python-client=2.183.0=pyh332efcf_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_1
  - google-generativeai=0.8.5=pyh29332c3_0
  - googleapis-common-protos=1.70.0=pyhd8ed1ab_0
  - grpcio=1.71.0=py313he3ef9dc_1
  - httplib2=0.31.0=pyhd8ed1ab_0
  - idna=3.7=py313hca03da5_0
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libgrpc=1.71.0=h857da87_1
  - libmpdec=4.0.0=h80987f9_0
  - libprotobuf=5.29.3=h6c9c1dd_2
  - libre2-11=2025.06.26=hd41c47c_0
  - libzlib=1.3.1=h5f15de7_0
  - multidict=6.6.3=py313h6347b5a_0
  - ncurses=6.5=hee39554_0
  - openssl=3.5.3=h5503f6c_1
  - pip=25.2=pyhc872135_0
  - propcache=0.3.1=py313ha9b7d5b_0
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.29.3=py313hfa7305b_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.23=py313hca03da5_0
  - pydantic=2.11.9=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313hf3ab51e_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py313hca03da5_0
  - python=3.13.7=hc28b8d9_100_cp313
  - python-dotenv=1.1.0=py313hca03da5_0
  - python_abi=3.13=1_cp313
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - re2=2025.06.26=h6589ca4_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py313hca03da5_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - setuptools=78.1.1=py313hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.5.0=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yarl=1.20.1=py313ha9b7d5b_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - anyio==4.11.0
      - google-genai==1.39.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - sniffio==1.3.1
      - tenacity==9.1.2
      - websockets==15.0.1
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/robots-txt
